name: Hit cron endpoint

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (GitHub Actions minimum)
  workflow_dispatch:        # allow manual run from the Actions tab

jobs:
  call-cron:
    runs-on: ubuntu-latest
    steps:
      - name: Curl cron endpoint
        run: |
          set -e
          echo "Calling $CRON_JOB_URL"
          curl -sS --max-time 25 "$CRON_JOB_URL"
        env:
          CRON_JOB_URL: ${{ secrets.CRON_JOB_URL }}
